export const IMAGE_SERVER_BASE_URL= "http://localhost:3003";
export const SPRING_BOOT_BASE_URL= "http://localhost:8080";
export const AUTH_TOKEN_DATA= "authTokenData";
export const EXPIRES_IN= 50;
export const AUTH_TOKEN= "AUTH_TOKEN";
export const CREATED_TIME= "CREATED_TIME";
export const AUTH_TOKEN_URL= "http://localhost:7080/realms/master/protocol/openid-connect/token";
export const ECOMMERCE_CLIENT_ID= "e-commerce-client-id";
export const ECOMMERCE_CLIENT_SECRET="hjchKkfcYFojZj1wliCAGeV2qgO6pyps";